general:
  productiveBranch: 'infrastructure-integration-test'
steps:
  cloudFoundryDeploy:
    dockerImage: localhost:5000/ppiper/cf-cli
stages:
  productionDeployment:
    cfTargets:
      - org: 'P2001099548trial_trial'
        space: 'dev'
        apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
        appName: 'devops-docker-images-IT'
        manifest: 'manifest.yml'
        credentialsId: 'devops-docker-images-IT-cf'
