on: push
name: Test
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - uses: SAP/project-piper-action@master
      with:
        command: artifactPrepareVersion
        piper-version: master
    - uses: SAP/project-piper-action@master
      with:
        command: mavenBuild
        piper-version: master
