name: Java CI

on: [push]

jobs:
  build:


    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Download Project Piper executable
      uses: SAP/devops-docker-cx-server/install-project-piper-action@install-piper-action

    - name: do something with piper
      run: |
        ls -la /opt/piper
        chmod +x /opt/piper
        /opt/piper
