on:
  push:
    branches: github-action
name: Test
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
    - name: Run Pipeline
      uses: SAP/devops-docker-cx-server/jenkinsfile-runner-github-action@master

